CURRENCY_API_LATEST_URL_TEMPLATE=https://latest.currency-api.pages.dev/v1/currencies/%s.json
CURRENCY_API_HISTORICAL_URL_TEMPLATE=https://%s.currency-api.pages.dev/v1/currencies/%s.json
CALENDAR_API_BASE_URL=https://date.nager.at/api/v3
CALENDAR_API_COUNTRY=TN
API_CONNECT_TIMEOUT_SECONDS=8
API_READ_TIMEOUT_SECONDS=12
